config:
  token: "TOKEN"
  dce_execpath: "F:\\programming_files\\DiscordChatExporter.Cli.win-x64\\DiscordChatExporter.Cli.exe" 
  intermediate_export_directory: "./s2000_json_exports"
  
  # --- Output Paths for Different Modes ---
  # For 'run-all' and 'scrape-roles' modes
  final_csv_output_path: "./s2000_aggregated_user_role_data.csv" 
  # For 'scrape-messages' mode
  messages_csv_output_path: "./s2000_scraped_messages.csv" 

  dce_export_format: "Json"
  dce_max_concurrent: 4
  channels:
    - id: "999380212280217670"
      name: "wow-lounge"
      autochunk:
        startdate: "2022-01-01"
        enddate: "2025-07-26" # Remember to update this to the current date
        chunkdurationmonths: 1
    - id: "999380527352135700"
      name: "help-me"
      autochunk:
        startdate: "2022-01-01"
        enddate: "2025-07-26" # Remember to update this to the current date
        chunkdurationmonths: 1
    - id: "1051771243751288842"
      name: "work-orders"
      autochunk:
        startdate: "2022-01-01"
        enddate: "2025-07-26" # Remember to update this to the current date
        chunkdurationmonths: 1
    - id: "1046836273542873191"
      name: "ayudame"
      autochunk:
        startdate: "2022-01-01"
        enddate: "2025-07-26" # Remember to update this to the current date
        chunkdurationmonths: 1
    - id: "1046836393038590022"
      name: "ayude-me"
      autochunk:
        startdate: "2022-01-01"
        enddate: "2025-07-26" # Remember to update this to the current date
        chunkdurationmonths: 1
    - id: "1046836576631664770"
      name: "arabic"
      autochunk:
        startdate: "2022-01-01"
        enddate: "2025-07-26" # Remember to update this to the current date
        chunkdurationmonths: 1
    - id: "1187726148390625301"
      name: "arabic-2"
      autochunk:
        startdate: "2022-01-01"
        enddate: "2025-07-26" # Remember to update this to the current date
        chunkdurationmonths: 1